package nl.torquelink.shared.enums.generic

import nl.torquelink.shared.enums.generic.CountryCode.entries


enum class CountryCode(
    val code: String,
    val isoCode: String,
    val secondIsoCode: String,
    val country: String
) {
    AF("93", "AF", "AFG", "Afghanistan"),
    AL("355", "AL", "ALB", "Albania"),
    DZ("213", "DZ", "DZA", "Algeria"),
    AS("1-684", "AS", "ASM", "American Samoa"),
    AD("376", "AD", "AND", "Andorra"),
    AO("244", "AO", "AGO", "Angola"),
    AI("1-264", "AI", "AIA", "Anguilla"),
    AQ("672", "AQ", "ATA", "Antarctica"),
    AG("1-268", "AG", "ATG", "Antigua and Barbuda"),
    AR("54", "AR", "ARG", "Argentina"),
    AM("374", "AM", "ARM", "Armenia"),
    AW("297", "AW", "ABW", "Aruba"),
    AU("61", "AU", "AUS", "Australia"),
    AT("43", "AT", "AUT", "Austria"),
    AZ("994", "AZ", "AZE", "Azerbaijan"),
    BS("1-242", "BS", "BHS", "Bahamas"),
    BH("973", "BH", "BHR", "Bahrain"),
    BD("880", "BD", "BGD", "Bangladesh"),
    BB("1-246", "BB", "BRB", "Barbados"),
    BY("375", "BY", "BLR", "Belarus"),
    BE("32", "BE", "BEL", "Belgium"),
    BZ("501", "BZ", "BLZ", "Belize"),
    BJ("229", "BJ", "BEN", "Benin"),
    BM("1-441", "BM", "BMU", "Bermuda"),
    BT("975", "BT", "BTN", "Bhutan"),
    BO("591", "BO", "BOL", "Bolivia"),
    BQ("599", "BQ", "BES", "Bonaire, Sint Eustatius and Saba"),
    BA("387", "BA", "BIH", "Bosnia and Herzegovina"),
    BW("267", "BW", "BWA", "Botswana"),
    BR("55", "BR", "BRA", "Brazil"),
    IO("246", "IO", "IOT", "British Indian Ocean Territory"),
    VG("1-284", "VG", "VGB", "British Virgin Islands"),
    BN("673", "BN", "BRN", "Brunei"),
    BG("359", "BG", "BGR", "Bulgaria"),
    BF("226", "BF", "BFA", "Burkina Faso"),
    BI("257", "BI", "BDI", "Burundi"),
    CV("238", "CV", "CPV", "Cabo Verde"),
    KH("855", "KH", "KHM", "Cambodia"),
    CM("237", "CM", "CMR", "Cameroon"),
    CA("1", "CA", "CAN", "Canada"),
    KY("1-345", "KY", "CYM", "Cayman Islands"),
    CF("236", "CF", "CAF", "Central African Republic"),
    TD("235", "TD", "TCD", "Chad"),
    CL("56", "CL", "CHL", "Chile"),
    CN("86", "CN", "CHN", "China"),
    CX("61", "CX", "CXR", "Christmas Island"),
    CC("61", "CC", "CCK", "Cocos (Keeling) Islands"),
    CO("57", "CO", "COL", "Colombia"),
    KM("269", "KM", "COM", "Comoros"),
    CG("242", "CG", "COG", "Congo (Brazzaville)"),
    CD("243", "CD", "COD", "Congo (Kinshasa)"),
    CK("682", "CK", "COK", "Cook Islands"),
    CR("506", "CR", "CRI", "Costa Rica"),
    CI("225", "CI", "CIV", "Côte d'Ivoire"),
    HR("385", "HR", "HRV", "Croatia"),
    CU("53", "CU", "CUB", "Cuba"),
    CW("599", "CW", "CUW", "Curaçao"),
    CY("357", "CY", "CYP", "Cyprus"),
    CZ("420", "CZ", "CZE", "Czechia"),
    DK("45", "DK", "DNK", "Denmark"),
    DJ("253", "DJ", "DJI", "Djibouti"),
    DM("1-767", "DM", "DMA", "Dominica"),
    DO("1-809, 1-829, 1-849", "DO", "DOM", "Dominican Republic"),
    EC("593", "EC", "ECU", "Ecuador"),
    EG("20", "EG", "EGY", "Egypt"),
    SV("503", "SV", "SLV", "El Salvador"),
    GQ("240", "GQ", "GNQ", "Equatorial Guinea"),
    ER("291", "ER", "ERI", "Eritrea"),
    EE("372", "EE", "EST", "Estonia"),
    SZ("268", "SZ", "SWZ", "Eswatini"),
    ET("251", "ET", "ETH", "Ethiopia"),
    FK("500", "FK", "FLK", "Falkland Islands"),
    FO("298", "FO", "FRO", "Faroe Islands"),
    FJ("679", "FJ", "FJI", "Fiji"),
    FI("358", "FI", "FIN", "Finland"),
    FR("33", "FR", "FRA", "France"),
    GF("594", "GF", "GUF", "French Guiana"),
    PF("689", "PF", "PYF", "French Polynesia"),
    TF("262", "TF", "ATF", "French Southern Territories"),
    GA("241", "GA", "GAB", "Gabon"),
    GM("220", "GM", "GMB", "Gambia"),
    GE("995", "GE", "GEO", "Georgia"),
    DE("49", "DE", "DEU", "Germany"),
    GH("233", "GH", "GHA", "Ghana"),
    GI("350", "GI", "GIB", "Gibraltar"),
    GR("30", "GR", "GRC", "Greece"),
    GL("299", "GL", "GRL", "Greenland"),
    GD("1-473", "GD", "GRD", "Grenada"),
    GP("590", "GP", "GLP", "Guadeloupe"),
    GU("1-671", "GU", "GUM", "Guam"),
    GT("502", "GT", "GTM", "Guatemala"),
    GG("44", "GG", "GGY", "Guernsey"),
    GN("224", "GN", "GIN", "Guinea"),
    GW("245", "GW", "GNB", "Guinea-Bissau"),
    GY("592", "GY", "GUY", "Guyana"),
    HT("509", "HT", "HTI", "Haiti"),
    HN("504", "HN", "HND", "Honduras"),
    HK("852", "HK", "HKG", "Hong Kong"),
    HU("36", "HU", "HUN", "Hungary"),
    IS("354", "IS", "ISL", "Iceland"),
    IN("91", "IN", "IND", "India"),
    ID("62", "ID", "IDN", "Indonesia"),
    IR("98", "IR", "IRN", "Iran"),
    IQ("964", "IQ", "IRQ", "Iraq"),
    IE("353", "IE", "IRL", "Ireland"),
    IM("44", "IM", "IMN", "Isle of Man"),
    IL("972", "IL", "ISR", "Israel"),
    IT("39", "IT", "ITA", "Italy"),
    JM("1-876", "JM", "JAM", "Jamaica"),
    JP("81", "JP", "JPN", "Japan"),
    JE("44", "JE", "JEY", "Jersey"),
    JO("962", "JO", "JOR", "Jordan"),
    KZ("7", "KZ", "KAZ", "Kazakhstan"),
    KE("254", "KE", "KEN", "Kenya"),
    KI("686", "KI", "KIR", "Kiribati"),
    KP("850", "KP", "PRK", "Korea (North)"),
    KR("82", "KR", "KOR", "Korea (South)"),
    KW("965", "KW", "KWT", "Kuwait"),
    KG("996", "KG", "KGZ", "Kyrgyzstan"),
    LA("856", "LA", "LAO", "Laos"),
    LV("371", "LV", "LVA", "Latvia"),
    LB("961", "LB", "LBN", "Lebanon"),
    LS("266", "LS", "LSO", "Lesotho"),
    LR("231", "LR", "LBR", "Liberia"),
    LY("218", "LY", "LBY", "Libya"),
    LI("423", "LI", "LIE", "Liechtenstein"),
    LT("370", "LT", "LTU", "Lithuania"),
    LU("352", "LU", "LUX", "Luxembourg"),
    MO("853", "MO", "MAC", "Macau"),
    MG("261", "MG", "MDG", "Madagascar"),
    MW("265", "MW", "MWI", "Malawi"),
    MY("60", "MY", "MYS", "Malaysia"),
    MV("960", "MV", "MDV", "Maldives"),
    ML("223", "ML", "MLI", "Mali"),
    MT("356", "MT", "MLT", "Malta"),
    MH("692", "MH", "MHL", "Marshall Islands"),
    MQ("596", "MQ", "MTQ", "Martinique"),
    MR("222", "MR", "MRT", "Mauritania"),
    MU("230", "MU", "MUS", "Mauritius"),
    YT("262", "YT", "MYT", "Mayotte"),
    MX("52", "MX", "MEX", "Mexico"),
    FM("691", "FM", "FSM", "Micronesia"),
    MD("373", "MD", "MDA", "Moldova"),
    MC("377", "MC", "MCO", "Monaco"),
    MN("976", "MN", "MNG", "Mongolia"),
    ME("382", "ME", "MNE", "Montenegro"),
    MS("1-664", "MS", "MSR", "Montserrat"),
    MA("212", "MA", "MAR", "Morocco"),
    MZ("258", "MZ", "MOZ", "Mozambique"),
    MM("95", "MM", "MMR", "Myanmar"),
    NA("264", "NA", "NAM", "Namibia"),
    NR("674", "NR", "NRU", "Nauru"),
    NP("977", "NP", "NPL", "Nepal"),
    NL("31", "NL", "NLD", "Netherlands"),
    NC("687", "NC", "NCL", "New Caledonia"),
    NZ("64", "NZ", "NZL", "New Zealand"),
    NI("505", "NI", "NIC", "Nicaragua"),
    NE("227", "NE", "NER", "Niger"),
    NG("234", "NG", "NGA", "Nigeria"),
    NU("683", "NU", "NIU", "Niue"),
    NF("672", "NF", "NFK", "Norfolk Island"),
    MK("389", "MK", "MKD", "North Macedonia"),
    MP("1-670", "MP", "MNP", "Northern Mariana Islands"),
    NO("47", "NO", "NOR", "Norway"),
    OM("968", "OM", "OMN", "Oman"),
    PK("92", "PK", "PAK", "Pakistan"),
    PW("680", "PW", "PLW", "Palau"),
    PS("970", "PS", "PSE", "Palestine"),
    PA("507", "PA", "PAN", "Panama"),
    PG("675", "PG", "PNG", "Papua New Guinea"),
    PY("595", "PY", "PRY", "Paraguay"),
    PE("51", "PE", "PER", "Peru"),
    PH("63", "PH", "PHL", "Philippines"),
    PN("870", "PN", "PCN", "Pitcairn Islands"),
    PL("48", "PL", "POL", "Poland"),
    PT("351", "PT", "PRT", "Portugal"),
    PR("1-787, 1-939", "PR", "PRI", "Puerto Rico"),
    QA("974", "QA", "QAT", "Qatar"),
    RE("262", "RE", "REU", "Réunion"),
    RO("40", "RO", "ROU", "Romania"),
    RU("7", "RU", "RUS", "Russia"),
    RW("250", "RW", "RWA", "Rwanda"),
    BL("590", "BL", "BLM", "Saint Barthélemy"),
    SH("290", "SH", "SHN", "Saint Helena"),
    KN("1-869", "KN", "KNA", "Saint Kitts and Nevis"),
    LC("1-758", "LC", "LCA", "Saint Lucia"),
    MF("590", "MF", "MAF", "Saint Martin"),
    PM("508", "PM", "SPM", "Saint Pierre and Miquelon"),
    VC("1-784", "VC", "VCT", "Saint Vincent and the Grenadines"),
    WS("685", "WS", "WSM", "Samoa"),
    SM("378", "SM", "SMR", "San Marino"),
    ST("239", "ST", "STP", "São Tomé and Príncipe"),
    SA("966", "SA", "SAU", "Saudi Arabia"),
    SN("221", "SN", "SEN", "Senegal"),
    RS("381", "RS", "SRB", "Serbia"),
    SC("248", "SC", "SYC", "Seychelles"),
    SL("232", "SL", "SLE", "Sierra Leone"),
    SG("65", "SG", "SGP", "Singapore"),
    SX("1-721", "SX", "SXM", "Sint Maarten"),
    SK("421", "SK", "SVK", "Slovakia"),
    SI("386", "SI", "SVN", "Slovenia"),
    SB("677", "SB", "SLB", "Solomon Islands"),
    SO("252", "SO", "SOM", "Somalia"),
    ZA("27", "ZA", "ZAF", "South Africa"),
    GS("500", "GS", "SGS", "South Georgia and the South Sandwich Islands"),
    SS("211", "SS", "SSD", "South Sudan"),
    ES("34", "ES", "ESP", "Spain"),
    LK("94", "LK", "LKA", "Sri Lanka"),
    SD("249", "SD", "SDN", "Sudan"),
    SR("597", "SR", "SUR", "Suriname"),
    SJ("47", "SJ", "SJM", "Svalbard and Jan Mayen"),
    SE("46", "SE", "SWE", "Sweden"),
    CH("41", "CH", "CHE", "Switzerland"),
    SY("963", "SY", "SYR", "Syria"),
    TW("886", "TW", "TWN", "Taiwan"),
    TJ("992", "TJ", "TJK", "Tajikistan"),
    TZ("255", "TZ", "TZA", "Tanzania"),
    TH("66", "TH", "THA", "Thailand"),
    TL("670", "TL", "TLS", "Timor-Leste"),
    TG("228", "TG", "TGO", "Togo"),
    TK("690", "TK", "TKL", "Tokelau"),
    TO("676", "TO", "TON", "Tonga"),
    TT("1-868", "TT", "TTO", "Trinidad and Tobago"),
    TN("216", "TN", "TUN", "Tunisia"),
    TR("90", "TR", "TUR", "Turkey"),
    TM("993", "TM", "TKM", "Turkmenistan"),
    TC("1-649", "TC", "TCA", "Turks and Caicos Islands"),
    TV("688", "TV", "TUV", "Tuvalu"),
    UG("256", "UG", "UGA", "Uganda"),
    UA("380", "UA", "UKR", "Ukraine"),
    AE("971", "AE", "ARE", "United Arab Emirates"),
    GB("44", "GB", "GBR", "United Kingdom"),
    US("1", "US", "USA", "United States"),
    UY("598", "UY", "URY", "Uruguay"),
    UZ("998", "UZ", "UZB", "Uzbekistan"),
    VU("678", "VU", "VUT", "Vanuatu"),
    VA("379", "VA", "VAT", "Vatican City"),
    VE("58", "VE", "VEN", "Venezuela"),
    VN("84", "VN", "VNM", "Vietnam"),
    WF("681", "WF", "WLF", "Wallis and Futuna"),
    EH("212", "EH", "ESH", "Western Sahara"),
    YE("967", "YE", "YEM", "Yemen"),
    ZM("260", "ZM", "ZMB", "Zambia"),
    ZW("263", "ZW", "ZWE", "Zimbabwe"),
    PRIVATE("****", "****", "****", "****");

    companion object {
        fun findCountryCode(representation: String) : CountryCode? {
            return entries.firstOrNull { country ->
                country.country == representation
                        || country.code == representation
                        || country.isoCode == representation
                        || country.secondIsoCode == representation
            }
        }

        fun checkCountry(representation: String) : Boolean {
            return entries.firstOrNull { country ->
                country.country == representation
                        || country.code == representation
                        || country.isoCode == representation
                        || country.secondIsoCode == representation
            }?.let { true } ?: false
        }
    }
}