package nl.torquelink.opendata.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class OpenDataVehicle(
    @SerialName("kenteken") val licensePlate: String,
    @SerialName("voertuigsoort") val vehicleType: String,
    @SerialName("merk") val brand: String,
    @SerialName("handelsbenaming") val tradeName: String,
    @SerialName("vervaldatum_apk") val expirationDateApk: String,
    @SerialName("datum_tenaamstelling") val registrationDate: String,
    @SerialName("bruto_bpm") val grossBpm: String,
    @SerialName("inrichting") val bodyType: String,
    @SerialName("aantal_zitplaatsen") val numberOfSeats: String,
    @SerialName("eerste_kleur") val primaryColor: String,
    @SerialName("tweede_kleur") val secondaryColor: String,
    @SerialName("aantal_cilinders") val numberOfCylinders: String,
    @SerialName("cilinderinhoud") val cylinderCapacity: String,
    @SerialName("massa_ledig_voertuig") val emptyVehicleMass: String,
    @SerialName("toegestane_maximum_massa_voertuig") val allowedMaximumMass: String,
    @SerialName("massa_rijklaar") val driveReadyMassWeight: String,
    @SerialName("maximum_massa_trekken_ongeremd") val maximumUnrestrainedMass: String,
    @SerialName("maximum_trekken_massa_geremd") val maximumRestrainedMass: String,
    @SerialName("datum_eerste_toelating") val firstAdmissionDate: String,
    @SerialName("datum_eerste_tenaamstelling_in_nederland") val firstRegistrationDateNetherlands: String,
    @SerialName("wacht_op_keuren") val waitingForInspection: String,
    @SerialName("wam_verzekerd") val wamInsured: String,
    @SerialName("aantal_deuren") val numberOfDoors: String,
    @SerialName("aantal_wielen") val numberOfWheels: String,
    @SerialName("europese_voertuigcategorie") val europeanVehicleCategory: String,
    @SerialName("plaats_chassisnummer") val chassisNumberLocation: String,
    @SerialName("technische_max_massa_voertuig") val technicalMaximumMass: String,
    @SerialName("typegoedkeuringsnummer") val approvalNumber: String,
    @SerialName("variant") val variant: String,
    @SerialName("uitvoering") val model: String,
    @SerialName("vermogen_massarijklaar") val readyMassPower: String,
    @SerialName("wielbasis") val wheelbase: String,
    @SerialName("export_indicator") val exportIndicator: String,
    @SerialName("openstaande_terugroepactie_indicator") val pendingRecallIndicator: String,
    @SerialName("taxi_indicator") val taxiIndicator: String,
    @SerialName("maximum_massa_samenstelling") val maximumAssemblyMass: String,
    @SerialName("jaar_laatste_registratie_tellerstand") val yearLastRegistrationMileage: String,
    @SerialName("tellerstandoordeel") val mileageAssessment: String,
    @SerialName("code_toelichting_tellerstandoordeel") val mileageAssessmentExplanationCode: String,
    @SerialName("tenaamstellen_mogelijk") val registrationPossible: String,
    @SerialName("vervaldatum_apk_dt") val expiryDateApkDt: String,
    @SerialName("datum_tenaamstelling_dt") val registrationDateDt: String,
    @SerialName("datum_eerste_toelating_dt") val firstAdmissionDateDt: String,
    @SerialName("datum_eerste_tenaamstelling_in_nederland_dt") val firstRegistrationDateNetherlandsDt: String,
    @SerialName("api_gekentekende_voertuigen_assen") val apiRegisteredVehiclesAxles: String,
    @SerialName("api_gekentekende_voertuigen_brandstof") val apiRegisteredVehiclesFuel: String,
    @SerialName("api_gekentekende_voertuigen_carrosserie") val apiRegisteredVehiclesBodywork: String,
    @SerialName("api_gekentekende_voertuigen_carrosserie_specifiek") val apiRegisteredVehiclesSpecificBodywork: String,
    @SerialName("api_gekentekende_voertuigen_voertuigklasse") val apiRegisteredVehiclesVehicleClass: String
)
